# Generated by Django 4.2.3 on 2023-08-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_ipaddress_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='AccountHits',
        ),
    ]
