# Generated by Django 4.2.3 on 2023-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
