# Generated by Django 4.2.3 on 2023-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0002_sociallinks_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicplayer',
            name='audio_link',
        ),
        migrations.AddField(
            model_name='musicplayer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
