# Generated by Django 4.2.3 on 2023-07-30 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0003_remove_musicplayer_audio_link_musicplayer_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicplayer',
            name='created',
        ),
        migrations.AddField(
            model_name='musicplayer',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
