# Generated by Django 4.2.3 on 2023-07-30 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0004_remove_musicplayer_created_musicplayer_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('album', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='video-cover')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
            ],
        ),
    ]
