# Generated by Django 4.2.3 on 2023-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0006_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='main_img',
            new_name='data_file',
        ),
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_file',
            new_name='data_file',
        ),
    ]
