# Generated by Django 4.2.3 on 2023-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0007_rename_main_img_gallery_data_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='musicplayer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
