# Generated by Django 4.2.3 on 2023-08-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0008_contactform_created_gallery_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
