# Generated by Django 4.2.3 on 2023-08-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0010_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactUs',
        ),
    ]
