# Generated by Django 4.2.3 on 2023-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0011_rename_contactform_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('u', 'Unread'), ('r', 'Read')], default='u', max_length=1),
        ),
    ]
